{% set name = "appium-python-client" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Appium-Python-Client-{{ version }}.tar.gz
  sha256: 8fc6825aa67c75ad1710a71586166770149a105ea1e23ee61bd308edcc62654c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - selenium >=3.14.1,<4

test:
  imports:
    - appium
    - appium.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://appium.io/
  summary: Python client for Appium
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
