{% set name = "appium-python-client" %}
{% set version = "3.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/appium_python_client-{{ version }}.tar.gz
  sha256: 79dc34119b1fe3ec0eae4fe31fb008184aed3e2837725fdbb1aadb7b64c62d39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - selenium ~=4.26,<5.0

test:
  imports:
    - appium
    - appium.common
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: http://appium.io/
  summary: Python client for Appium
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - nisharai1
