{% set name = "appium-python-client" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Appium-Python-Client-{{ version }}.tar.gz
  sha256: 1152b6aea245fad12a73b0015a64df0636cc2f4fb11c9a3e27b6c9082cd44429

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - selenium >=3.14.1,<4

test:
  imports:
    - appium
    - appium.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://appium.io/
  summary: Python client for Appium
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
